### ISSUE TITLE
Country code weren't being properly parsed back after being written to preferences

### ISSUE THREAD

**Issue by ghost** [titinko/utsu#47] opened 2020-12-02 08:29 UTC
Version: 0.4.3
Platform: 64-bit Linux

If you changed some config and restart utsu, the config will take no effect.

**Comment by titinko** [comment] 2020-12-02 08:43
I can't reproduce this on my own Linux so it may be something specific to your computer's setup.  In the backend, preferences are stored in a .utsu folder in your home directory, which is the default directory that will show up if you open a terminal window.  Could you check if there's a .utsu folder in your filesystem and, if so, if the folder has your preferences stored in .utsu/0.5/preferences.xml?

**Comment by Hiasinsu** [comment] 2020-12-02 09:24
I checked .utsu directory, the file .utsu/0.5/preferences.xml exists.
Then I find this probably is not a bug about preferences loading, because it looks only affect language preference.
When you set language to FR, zh_CN, zh_TW, BR, RU and restart utsu, then language will be set to default, but set to other language won't be like this.

**Comment by titinko** [comment] 2020-12-03 04:27
Was able to reproduce the bug, but only with the following four languages: French, Chinese Simplified, Chinese Traditional, and Brazilian Portuguese.  What happened was that languages with a country code weren't being properly parsed back after being written to preferences.

The fix for this bug should show up in the next release.

**Comment by Hiasinsu** [comment] 2020-12-03 05:07
Thank you for spending time to fix this.

😉

**Comment by titinko** [comment] 2021-02-16 05:14
Fixed with v0.4.4.

**Closed by titinko** 2021-02-16 05:14 UTC
Labels: bug
